name: Validate

on:
  push:
  pull_request:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check required files
        run: |
          test -f hacs.json
          test -f README.md
          test -f dist/eight-sleep-card.js
